export const PlacementJobLocators = {
    postJobButton: '#post-placement-job-btn',
    postJobFields: (field: string) =>
        `xpath=(//div[@data-test-id="text-box-with-label"][.//span[text()="${field}"]]//input)`,
    titleInputField: '[data-test-id="text-box-with-label-title"] input',
    addressInputField: '[data-test-id="text-box-with-label-address1"] input',
    cityInputField: '[data-test-id="text-box-with-label-city"] input',
    stateInputField: '[data-test-id="text-box-with-label-provincestate"] input',
    countryInputFiled: '[data-test-id="text-box-with-label-country"] input',
    zipCodeInputField: '[data-test-id="text-box-with-label-postal_code"] input',
    compensationInputField: '[data-test-id="text-box-with-label-compensation"] input',
    startDateInputField: '[data-test-id="text-box-with-label-start_date_text"] input',
    childrenInputField: '[data-test-id="text-area-with-label-children_description"] input',
    scheduleInputField: '[data-test-id="text-area-with-label-text"] input',
    babyCareCheckbox: '[data-test-id="checkbox-Baby Care"]',
    dailyTasksInputField: '[data-test-id="text-area-with-label-info__23195_3"] input',
    childrenField: '(//textarea[@data-test-id="text-area"])[1]',
    scheduleField: '(//textarea[@data-test-id="text-area"])[2]',
    caregiverQualitiesField: '(//textarea[@data-test-id="text-area"])[3]',
    dailyTasksField: '(//textarea[@data-test-id="text-area"])[4]',
    familyCommentsField: '(//textarea[@data-test-id="text-area"])[5]',
    postButton: 'button[data-test-id="post-button-placement-job"]',
    closeButton: '//button[contains(text(),"Close")]',
    createdJobTitle: (title: string) => `//h4[contains(@class, "job-title") and text()="${title}"]`,
    placementJobSearchIcon: '//i[contains(text(),"search")]',
    placementJobSearchBar: ' (//input[@id="searchBar"])[1]',
    placementJobDeleteIcon: '(//i[contains(text(), "delete")])[1]', //'//div[@class="icon-btn-container mr-2 icon-btn has-tooltip"][4]', //i[contains(text(), "delete")]
    placementJobDeleteButton: '[data-test-id="accept-button"]',//span[contains(text(),"Delete")]',
    addNoteIcon: '//i[contains(text(),"add_circle_outline")]',
    noteInputBox: '[data-test-id="text-editor-unknown"]',
    addNoteButton: '//button[contains(text(),"Add Note")]',
    noteContent: '[class="note-content"]',
    noteContentText: '[class="note-content"] pre',
    deleteNoteIcon: '[class="action-button delete-button has-tooltip"]',
    placementJobInputFieldsProd: '[class="position-relative input-container"] input',
    editButton: '[class="mylisting-button dark-button mb-2 mb-md-2 mr-2"]',
    closeEditButton: '[data-test-id="modal-dialog-close-button"]',
    checkStart: '[data-test-id="placement-job-start_date_text-value"]',
    checkCompensation: '[data-test-id="placement-job-compensation-value"]',
    checkSchedule: '[data-test-id="placement-job-text-value"]',
    checkChildren: '[data-test-id="placement-job-children_description-value"]',
    checkCountry: '[data-test-id="placement-job-country-value"]',
    checkZipCode: '[data-test-id="placement-job-postal_code-value"]',
    checkAddress: '[data-test-id="placement-job-address1-value"]',
    checkTitle: '[data-test-id="placement-job-title-value"]',
    checkState: '[data-test-id="placement-job-provincestate-value"]',
    checkLocation: '[data-test-id="placement-job-locations-value"]',
    locationField: '[data-test-id="multi-select-with-label-locations"]',
    chooseLocation: '[id="multi-select-with-label-locations-0"]',
    jobTitleOnCandidateProfile: '[class="card-title"]',
    jobStatus: '[class="job-status"]',
    availableJobsOnCandidateProfile: '[data-test-id="menu-bar-Available Jobs"]',
    filterCleaningOnCandidateProfileAvailableJos: '[class="multiselect__tag-icon"]',
    switchToTableView: '(//i[contains(text(), "table")])[2]',
    placementJobTableGearIcon: '[class="setting-container ml-1 web-only web-only"]',
    labelsDropdown: '[data-test-id="multiselect-select-field"]',
    searchToggle: 'button[aria-labelledby="expandable-filters-label"]',
    AIJobAnalysis: '[class="material-icons ml-2 ai-job-analysis-icon has-tooltip"]'
};