export const ToDoLocators = {
    toDoIcon: '[class="material-symbols-outlined is-icon-outlined big-size"]',
    allToDoView: '[class="icon-btn-container icon-btn has-tooltip"]',
    fullView: '//i[contains(text(), "open_in_full")]',
    iconBarToDoTasks: '[class="get-started-item todo-notification-btn"]',
    toDoModal: '[class="icon-btn-container icon-btn has-tooltip"]',
    addToDoItem: '[class="add-todo-button has-tooltip"]',
    title: 'input[placeholder="Eg. Follow up with Jones family"]',
    createToDoButton: 'button[class="mylisting-button dark-button absolute-right-bottom"]',
    tableRow: '[data-test-id="data-table-row"]',
    tableView: '[class="data-table--table table table-striped mt-2"]',
    deleteToDo: '//i[contains(text(), " delete ")]',
    acceptDeleteTask: '[data-test-id="accept-button"]',
    acceptReassignTask: '[data-test-id="accept-button"]',
    toDoGearIcon: '[class="material-icons cursor-pointer calendar-top-icons mr-3 has-tooltip"]',
    labelToDoTasks: '//h4[contains(text(), "To Do Tasks")]',
    settingsCheckbox: 'div[data-test-id="checkbox-item-public_advance_setting.show_task_planner_kanban_view_by_default"]',
    moreFilters: '//i[contains(text(), "search")]',
    kanbanView: '[class="kanban-board mt-2"]',
    kanbanToggleCheckbox: '[data-test-id="checkbox-item-undefined"]',
    dontSendButton: '//button[contains(text(),"Don\'t Send")]',
    analyseAndAutoFill:'[class="mylisting-button dark-button w-100"]',
    assignedAdmin: 'td[data-test-id="-Assign To"]',
    sendButton: '//button[contains(text(),"Send") and not(contains(text(),"Don\'t"))]',
}