export const CandidatesPageLocators = {
  addNewCandidateButton: '[data-test-id="candidate-add-user"]',
  emailInputField: '.email-textbox input',
  phoneNumberInputField: '//label[.//span[contains(text(),"Phone Number")]]/following-sibling::div//input',
  firstNameInputField: '//label[.//span[contains(text(),"First Name")]]/following-sibling::div//input',
  lastNameInputField: '//label[.//span[contains(text(),"Last Name")]]/following-sibling::div//input',
  addButton: '//button[contains(text(),"Add")]',
  dontSendButton: '//button[contains(text(),"Don\'t Send")]',
  deleteCandidateButton: '//p[contains(text(),"Delete Candidate")]',
  modalWindowCloseButton: '.close-button-container i',
  deleteButton: '.accept-btn-container button',
  searchField: '//div[@class="search-add-row d-flex"] //input ',
  emptyTableText: '[data-test-id="table-pagination-info"]',
  noteButton: '#menu-bar-notes',
  addNoteButton: '[class="icon-btn-container my-2 icon-btn has-tooltip"]',
  noteDialogModal: '[data-test-id="note-dialog-modal"]',
  noteInputBox: '.content-editable',
  modalAddNoteButton: '.mylisting-button.dark-button.absolute-right-bottom',
  closeButton: '.mylisting-button.secondary-button.close-btn',
  candidateList: '[data-test-id="data-table-row"]',
  candidateEmailLocator: '//td//span[contains(text(),"testcandidate@gmail.com")]',
  adminsToNotifyField: '[placeholder="Admins to Notify"]',
  userTypeDropdown: '[data-test-id="multi-select-with-label-selector1"]',
  userType: '//span[contains(text(),"Spanish Speaking")]',
  inputOptionDropdown: '[placeholder="Search options"]',
  deleteNoteButton: '//button[contains(text(),"Delete Note")]',
  noteTextLocator:(note: string) =>
    `//pre[contains(text(),"${note}")]`,
  selectCandidateCheckbox: '[data-test-id="form-check-row"] input',
  deleteSelectedButton: '//button[contains(text(),"Delete Selected")]',
  advancedSearchIcon: '//div//i[contains(text(),"manage_search")]',
  advancedSearchFormViewSection: '//button[contains(text(),"Form View")]',
  spanishSpeakingCheckbox: '[data-test-id="checkbox-Spanish Speaking"]',
  advancedSearchButton: '//button[contains(text(),"Search")]',
  candidateProfileList: '[class="list-menu-item-not-float list-item-in-dialog dialog-scrolled"]',
  schemaIcon: '[data-test-id="candidate-schema"]',
  adminView: '[id="menu-bar-admin"]',
  profileView: '[id="menu-bar-profile"]',
  referenceStatus: '[class="ml-2 has-tooltip"]',
  warningIcon: '[class="report-icon has-tooltip"]',
  contactInfoEdit: '[data-test-id="edit-button-profile-section"]',
  contactEditNameField: '[data-test-id="text-box-with-label-first_name"]',
  saveContactInfoSave: '[class="submit-button mylisting-button dark-button"]',
  resumeViewButton: '[class="action-btn action-btn--primary btn-desktop-visible"]',
  resumeView: '[class="p-2 preview-in-dialog"]',
  filterButtonInCandidateSearch: '[class="icon-btn-container ml-2 icon-btn has-tooltip"]',
  candidateKeywordSearch: '[data-test-id="candidate-table-search-and-filter"]',
  myScheduleTab: '[data-test-id="menu-bar-My Schedule"]',
  recurringAvailability: '//button[contains(text(),"Recurring Availability")]',
  recurringAvailabilitySetting: '[class="d-flex align-items-center mt-4"] [title="Settings"]',
  maximumNumOfHours: '//label[contains(text(),"Maximum number of bookings can have in one day")]',
  addedDocumentName: '//h5[contains(text()," W-4 ")]',
  statusDropdown: '[class="multiselect-container panel--select-status--multiselect"]',
  searchAndFilterTool: '[data-test-id="candidate-table-search-and-filter"]',
  allCandidateInTableCheckbox: 'input[class=" has-tooltip"]',
  confirmDelete: '[class="accept-btn-container"] button'
};
