export const ClientPageLocators = {
  addClientButton: '[data-test-id="client-add-user"]',
  emailInputField: '.email-textbox input',
  phoneNumberInputField: '//label[.//span[contains(text(),"Phone Number")]]/following-sibling::div//input',
  firstNameInputField: '//label[.//span[contains(text(),"First Name")]]/following-sibling::div//input',
  lastNameInputField: '//label[.//span[contains(text(),"Last Name")]]/following-sibling::div//input',
  addButton: '//button[contains(text(),"Add")]',
  dontSendButton: '//button[contains(text(),"Don\'t Send")]',
  clientTable: '[data-test-id="client-data-table"] table',
  deleteClientButton: '[class="mt-3 delete-client-btn"]',
  addAdminNotesButton: '.align-center i',
  adminModalCloseButton: '[class="mylisting-button secondary-button close-btn"]',
  noteTextField: '[class="content-editable"]',
  addedNoteModal: '[data-test-id="note-dialog-modal"]',
  notesModalCancelButton: '//button[contains(text(),"Cancel")]',
  selectClientCheckbox: '[data-test-id="form-check-row"]',
  deleteSelectedButton: '//button[contains(text()," Delete Selected ")]',
  deleteSecondaryLoginButton: '//i[contains(text()," delete ")]',
  confirmDelete: '[class="accept-btn-container"]',
  schemaIcon: '[data-test-id="client-schema"]',
  clientTableMobile: '[data-test-id="client"]',
  searchClientField: '[id="client-name-email-phone-search"]',
  clientPage: '[data-test-id="data-table-row"] [class="max-content"]',
  clientPageView2Table: '[data-test-id="-Email"] [class="max-content"]',
  adminView: '[data-test-id="menu-bar-admin"]',
  profileView: '[id="menu-bar-application"]',
  moreSection: '[data-test-id="menu-bar-more"]',
  UploadDocumentButton: '(//i[contains(text(), "upload_file")])[2]',
  statusDropdownTrigger: '[data-test-id="-Status"] .multiselect__select',
  statusDropdownContent: '[data-test-id="-Status"] .multiselect__content-wrapper',
  statusDropdownOptions: '[data-test-id="-Status"] .multiselect__element',
  acceptModalButton: '[data-test-id="accept-button"]',
  menuBarPasswordsTab: '[id="menu-bar-password"]',
  addSecondaryLogin: '//button[contains(text(), " Add Secondary Logins ")]',
  fieldSecondaryName: 'input[data-test-id="text-box-with-label-first_name"]',
  fieldSecondaryEmail: 'input[data-test-id="text-box-with-label-email"]',
  fieldSecondaryPassword: 'input[data-test-id="text-box-with-label-password"]',
  submitButton: '//button[contains(text()," Submit ")]',
  deleteSecondUser: '[class="material-icons delete-icon has-tooltip"]',
  searchAndFilterTool: '[data-test-id="client-table-search-and-filter"]',
  editProfileSection: '[data-test-id="edit-button-profile-section"]',
  saveButton: '//button[contains(text(),"Save")]',
  closeEditButton: '[data-test-id="modal-dialog-close-button"]'
};
