export const ApplicationAndProfileBuilderLocators = {
    addButton: '[data-test-id="button-add-profile-builder"]',
    nameField: '[data-test-id="input-profile-name"]',
    applicationRadioButton: '[id="type-Application"]',
    candidateRadioButton: '[id="type-Candidate"]',
    searchField: '[placeholder="Search by Name, Subject, or Content"]',
    addFieldButton: '[data-test-id="button-add-field"]',
    questionField: '[data-test-id="input-field-label"]',
    fieldType: '[id="multiselect-field-type0"]',
    fieldOption: '//span[contains(text(), "Textarea")]',
    yesButton: '[class="mylisting-button danger-button"]',
    clickSubmit: '[data-test-id="button-save-profile"]',
    builderNameSearchBox: '[data-test-id="input-search-application-builder"]',
    viewFormButton: '[data-test-id="view-application-form"]',
    editButton: '[class="material-icons modify-builder-property has-tooltip"]',
    nameLocator: '[class="center mb-3 heavy-font mt-4"]',
    delBuilder: '//i[contains(text(), "delete")]',
    delButton: '//span[contains(text(),"Delete")]',
    editNameBox: 'input.form-control.input-text.space-top',
    editName: 'div.d-flex.align-items-center h2 i',
    nameTest: '//table//tr/td[2]/div/span',
    locationCheckbox: 'input[data-test-id="checkbox-New York"]',
    firstNameClientForm: '[data-test-id="text-box-with-label-first_name"] input',
    phoneNumberStg: '[data-test-id="text-box-with-label-phone"] input',
    phoneNumberProd: '[data-test-id="text-box-with-label-info__custom_phone1"] input',
    emailClientFormStg:'[class="form-control"]',
    emailClientFormProd: '[data-test-id="text-box-with-label-text15"] input',
    addressClientFormStg: '[data-test-id="text-box-with-label-address1"] input',
    addressClientFormProd: '[data-test-id="text-box-with-label-text16"] input',
    cityClientFormStg:'[data-test-id="text-box-with-label-city"] input',
    cityClientFormProd: '[data-test-id="text-box-with-label-text18"] input',
    gearIcon: '//i[contains(text(), " settings ")]',
    notificationsTab: '//button[contains(text(),"Notifications")]',
    sendSubmissionNotificationOption: '[id="email-submission-yes"]',
    submissionNotificationEmailField: 'div[class="row-container"]',
    sendSummaryToApplicantCheckbox: '[data-test-id="checkbox-item-checkbox-notify-applicant"]',
    closeSettingsButton: '[data-test-id="modal-dialog-close-button"]',
    logSearchIcon: '//i[contains(text(), "search")]',
    logSearchSubjectField: '[placeholder="Search by subject line"]',
    logItems: '[class="log-item--body--items"]',
    submitButtonApplicationForm: 'div button[id="submit-button"]'
};
