export const DashboardLocators = {
  searchField: '[data-test-id="client-name-email-phone-search-and-other-filters"] input',
  schemaIcon: '//i[contains(text(),"schema")][1]',
  workflowButton:(workflow: string) => `//span[contains(text(),"${workflow}")]`,
  processFlowTitle: '//h3[contains(text(),"Process Flow")]',
  searchIcon: '[data-test-id="icon-button-shift-job-search-and-filter"]',
  searchIconCandidatePage: '[data-test-id="candidate-table-search-and-filter"]',
  emptyTableText: '//span[contains(text(),"1 to 0 of 0 entries")]',
  moreSection: 'li [data-test-id="More"]',
  calculatorSection: '[data-test-id="Burden Calculator"]',
  allLogsButton: '//div[contains(text(),"All Logs")]',
  filterClearButton: '[data-test-id="multi-select-clear-button"]',
  appAndProfileBuilder: '[data-test-id="Application & Profile Builder"]',
  profileSection: '#menu-bar-profile',
  addDocumentTemplateButton: '[data-test-id="add-button-dropdown-documents"]',
  confirmDeleteTemplateButton: '[data-test-id="accept-button"]',
  dontSendButton: '//button[contains(text(),"Don\'t Send")]',
  signButton: '//button[contains(text(),"Sign")]',
  dateField: '[placeholder="MM/DD/YYYY"]',
  globalSettingsButton: '[data-test-id="Agency Context"]',
  searchInGlobalSettings: '[class="form-search w-full search"]',
  dashboardDropdownMobile: '[class="navbar-toggler-icon"]',
  closeButton: '[data-test-id="modal-dialog-close-button"]',
  logoutButton: '[data-test-id="Logout"]'
};