export const ShiftJobLocators = {
    nextYearArrow: '[class="nextYear"]',
    noteTextArea: '[data-test-id="text-area"]',
    selectFamiliesInput: '(//*[@id="multiselect-select-field"])[1]',
    bookingAddressInput: '[data-test-id="text-box-with-label-address1"] input',
    cityInput: '[data-test-id="text-box-with-label-city"] input',
    provinceInput: '[data-test-id="text-box-with-label-provincestate"] input',
    zipCodeInput: '[data-test-id="text-box-with-label-postal_code"] input',
    submitButton: '[data-test-id="button-save-shift-job"]',
    testUserSelector: '//span[contains(text(),"testuser@enginehire.ca")]',
    howManyChildrenWillBeCaredForInput: '(//*[@id="multiselect-select-field"])[3]',
    yesButton: '//span[contains(text(),"Yes")]',
    clientBillingRateInput: '(//div[contains(@class, "position-relative") and contains(@class, "input-container")]//textarea)[2]',
    addressLine2Input: '[data-test-id="text-box-with-label-address2"] input',
    agencyBookingFeeInput: '(//*[@class="position-relative input-container"]//input)[2]',
    baseRateInput: '(//*[@class="position-relative input-container"]//input)[1]',
    assignThisJobInput: '(//*[@id="multiselect-select-field"])[2]',
    tableSection: '//div//div[@id=\'menu-bar-Table\']',
    daySection: '[data-test-id="menu-bar-Day"]',
    weekSection: '[data-test-id="menu-bar-Week"]',
    monthSection: '[data-test-id="menu-bar-Month"]',
    schedulerSection: '[data-test-id="menu-bar-Scheduler"]',
    analyticsSection: '[data-test-id="menu-bar-Analytics"]',
    timeOffSection: '[data-test-id="menu-bar-Time Off"]',
    shiftReportsSection: '[data-test-id="shift-job-shift-reports"]',
    cancelButton: '//i[contains(text(),"cancel")]',
    shiftJobCheckbox: '[class="form-check-input"]',
    deleteSelectedButton: '//button[contains(text(),"Delete Selected")]',
    confirmDelete: '[class="accept-btn-container"] button',
    sendEmailButton: '//button[contains(text(),"Send Email")]',
    emailSmsPushNotificationLog: '//h4[contains(text(),"Email/SMS/Push/AI Voice Log")]',
    communicationChannelRadioButtons:(index: number) => `input[id="Audience${index}"]`,
    sendButton: '//button[contains(text(),"Send")]',
    clientTypeClearIcon: '[class="multiselect__tag-icon"]',
    channelCard: '[class="channel-card"]',
    numberFillerNeededField: '[data-test-id="drop-down-with-label"] select',
    closeLogsModalButton: '[data-test-id="button-close-logs"]',
    shiftJobStatus:(status: string) => `//span[contains(text(),"Current Status: ${status}")]`,
    createdShiftJobModal: '[data-test-id="modal-dialog-close-button"]',
    bookingSection:'[data-test-id="multi-select-with-label-section_builder_id"]',
    inputBookingSection: '[id="multi-select-with-label-section_builder_id"]',
    broadcastCheckbox: 'div[data-test-id="checkbox-item-is_broadcast"] input',
    clientEmailInForm: '[data-test-id="multi-select-with-label-poster"] span',
    candidateEmailInform: '[data-test-id="multi-select-with-label-filler"] span',
    clientTextInForm: '[data-test-id="multi-select-with-label-poster"] .multiselect__tags .multiselect__single',
    candidateTextInform: '[data-test-id="multi-select-with-label-filler"] .multiselect__tags .multiselect__single',
    unassignCandidateButton: '//button[contains(text()," Unassign Candidate")]',
    confirmUnassignCandidateModalText: '//h2[contains(text(),"Are you sure you want to unassign test?")]',
    confirmUnassignCandidateButton: '[class="accept-btn-container"]',
    unassignedCandidateText: '//span[contains(text()," candidate is unassigned")]',
    sendEmail: '//button[contains(text(),"Send Email")]',
    tableMobile: '//span[contains(text(),"table")]',
    clientsInDropdown: '[data-test-id="multi-select-with-label-poster"] [class="multiselect__option"]',
    candidatesDropdown: '[data-test-id="multi-select-with-label-filler"]',
    allJobsCheckboxInTable: '[class=" has-tooltip"]',
    shiftJobFormTitle: '[class="dialog-title"]',
    conflictSectionTitle: 'th [data-test-id="users-Conflicts"]',
    calendarWeekdays: '.cv-header-day[class*="dow"]',
    calendarDays: '[class="cv-day-number"]',
    calendarRows: '[class="cv-weeks"]',
    refreshButton: '[class="filter-refresh has-tooltip"]',
    multiDayShifts: '[class="view-job-btn ml-2"]'
};
